# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4fccf105f07cc1b83d75cc0a47e06285bd374ec66ac8d9869c6ad680dc9a3b33294b6b01b78d4ce631c14b9ba0cfa7d01242bd76f143da1a57dc6ffe684d362

test:
  secret_key_base: 9348d528bbd47494a98027a6d9d6d706da0c4b6653fc37a0001863cd9d7acf889beb6ca45c31feaec24e6ccc43f3e46f8e8c5f41765b1d7428e2fa471e237002

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
